baragiola_moni/prestamos/urls.py
from django.urls import path

from baragiola_moni.prestamos import views

app_name = 'prestamos'
urlpatterns = [
    path(
        'pedidos/',
        view=views.PedidosList.as_view(),
        name='pedido-list'
    ),
    path(
        'pedidos/add/',
        view=views.PedidoCreateView.as_view(),
        name='pedido-create'
    ),
    path(
        'pedidos/<int:pk>/',
        view=views.PedidoDetailView.as_view(),
        name='pedido-detail'
    ),
    path(
        'pedidos/<int:pk>/edit/',
        view=views.PedidoUpdateView.as_view(),
        name='pedido-update'
    )
]

baragiola_moni/users/urls.py
from django.urls import path

from baragiola_moni.users.views import user_detail_view, user_list_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from baragiola_moni.prestamos.views import PedidoCreateView

urlpatterns = [
    path('', view=PedidoCreateView.as_view(), name='home'),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("baragiola_moni.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("prestamos/", include("baragiola_moni.prestamos.urls", namespace="prestamos")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

baragiola_moni/prestamos/models.py
from django.db import models
from django.urls import reverse

GENERO_MASCULINO = 'M'
GENERO_FEMENINO = 'F'
GENEROS = (
    (GENERO_MASCULINO, 'Masculino'),
    (GENERO_FEMENINO, 'Femenino')
)


class Pedido(models.Model):
    """
    Los clientes pueden pedir préstamos online sin registrarse
    en la plataforma.
    Los pedidos son autorizados o denegados utilizando una API de
    terceros.
    """
    dni = models.CharField(
        'DNI',
        max_length=10
    )
    nombre = models.CharField(
        'nombre',
        max_length=50
    )
    apellido = models.CharField(
        'apellido',
        max_length=50
    )
    genero = models.CharField(
        'genero',
        max_length=1,
        choices=GENEROS
    )
    email = models.EmailField(
        'email'
    )
    monto = models.DecimalField(
        'monto',
        max_digits=15,
        decimal_places=2
    )
    autorizado = models.BooleanField(
        'autorizado',
        blank=True,
        default=False
    )
    borrado = models.BooleanField(
        'borrado',
        blank=True,
        default=False
    )
    fecha = models.DateTimeField(
        'fecha',
        auto_now_add=True
    )
    fecha_ultima_modificacion = models.DateTimeField(
        'fecha última modificación',
        auto_now=True
    )

    def __str__(self):
        return "%(apellido)s, %(nombre)s (%(dni)s) - %(fecha)s" % {
            'apellido': self.apellido,
            'nombre': self.nombre,
            'dni': self.dni,
            'fecha': self.fecha.strftime('%d-%m-%Y %H:%M')
        }

    def get_absolute_url(self):
        return reverse('prestamos:pedido-detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'pedido'
        verbose_name_plural = 'pedidos'
        default_permissions = ('add', 'change', 'delete', 'view')
        ordering = ['-fecha', 'apellido', 'nombre']

baragiola_moni/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

baragiola_moni/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

baragiola_moni/prestamos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from baragiola_moni.prestamos import models


class PedidoDetailView(LoginRequiredMixin, DetailView):
    model = models.Pedido
    context_object_name = 'pedido'
    template_name = 'prestamos/pedido_detail.html'


class PedidoCreateView(CreateView):
    model = models.Pedido
    fields = ['dni', 'nombre', 'apellido', 'email', 'genero', 'monto']
    template_name = 'prestamos/pedido_add.html'


class PedidosList(LoginRequiredMixin, ListView):
    template_name = 'prestamos/pedidos_list.html'
    context_object_name = 'pedidos'

    def get_queryset(self):
        return models.Pedido.objects.filter(borrado=False)


class PedidoUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Pedido
    fields = [
        'dni',
        'nombre',
        'apellido',
        'email',
        'genero',
        'monto',
        'autorizado',
        'borrado'
    ]
    template_name = 'prestamos/pedido_edit.html'

baragiola_moni/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

baragiola_moni/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

baragiola_moni/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}baragiola-moni{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'prestamos:pedido-create' %}">baragiola-moni</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'prestamos:pedido-list' %}">Préstamos<span class="sr-only"></span></a>
            </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'prestamos:pedido-create' %}">Solicitar Préstamo</a>
              </li>
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 

baragiola_moni/templates/pages/about.html
{% extends "base.html" %}

baragiola_moni/templates/pages/home.html
{% extends "base.html" %}

baragiola_moni/templates/prestamos/pedido_add.html
{% extends "base.html" %}
  
{% load i18n %}

{% block title %}Solicitar Préstamo{% endblock %}

{% block content %}
  <h1>Pedido {{ pedido.id }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'prestamos:pedido-create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Solicitar</button>
      </div>
    </div>
  </form>
{% endblock %}

baragiola_moni/templates/prestamos/pedido_detail.html
{% extends "base.html" %}

{% block title %}Detalle Pedido{% endblock %}

{% block content %}
<div class="row">
  <div class="col"><h1>Pedido #{{ pedido.id }}</h1></div>
</div>
<div class="row">
  <div class="col">DNI: {{ pedido.dni }}</div>
</div>
<div class="row">
  <div class="col">Nombre: {{ pedido.nombre }}</div>
</div>
<div class="row">
  <div class="col">Apellido: {{ pedido.apellido }}</div>
</div>
<div class="row">
  <div class="col">Email: {{ pedido.email }}</div>
</div>
<div class="row">
  <div class="col">
    Género:
    {% if pedido.genero == "M" %}
        Masculino
    {% elif pedido.genero == "F" %}
        Femenino
    {% else %}
        Desconocido
    {% endif %}
  </div>
</div>
<div class="row">
  <div class="col">Monto: $ {{ pedido.monto }}</div>
</div>
<div class="row">
  <div class="col">
    Autorizado:
    {% if pedido.autorizado %}
        Sí
    {% else %}
        No
    {% endif %}
  </div>
</div>
<div class="row">
  <div class="col">
  Creado el {{ pedido.fecha }}.
  </div>
</div>
{% if pedido.fecha != pedido.fecha_ultima_modificacion %}
<div class="row">
  <div class="col">
   Última modificación el {{ pedido.fecha_ultima_modificacion }}.
  </div>
</div>
{% endif %}
{% endblock %}

baragiola_moni/templates/prestamos/pedido_edit.html
{% extends "base.html" %}
  
{% block title %}Actualizar Pedido{% endblock %}

{% block content %}
  <h1>Pedido #{{ pedido.id }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'prestamos:pedido-update' pedido.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Actualizar</button>
      </div>
    </div>
  </form>
{% endblock %}

baragiola_moni/templates/prestamos/pedido_list.html
{% extends "base.html" %}
  
{% block title %}Lista de Pedidos{% endblock %}

{% block content %}
<div class="row">
  <div class="col"><h1>Pedidos</h1></div>
</div>
<div class="row">
  <div class="col">
    <ul>
      {% for pedido in pedidos %}
      <div class="row">
        <div class="col">
          <a href="{% url 'prestamos:pedido-detail' pedido.id %}">
            <b>{{ pedido }}</b>
          </a>
        </div>
        <div class="col">
          <a href="{% url 'prestamos:pedido-update' pedido.id %}">
            <b>EDITAR</b>
          </a>
        </div>
      </div>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

baragiola_moni/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

baragiola_moni/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

baragiola_moni/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}